pipeline {
    agent any

    stages {

        stage('Clone Repo') {
            steps {
                git 'https://github.com/NikitaKotambe03/aws-production-webapp.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t myapp ./app'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker stop myapp || true'
                sh 'docker rm myapp || true'
                sh 'docker run -d -p 80:80 --name myapp myapp'
            }
        }
    }
}